[book]
authors = ["PubMed Miner"]
language = "en"
src = "book_src"
title = "Daily Essential Papers"

[output.html]
additional-css = ["book_src/custom.css"]
git-repository-url = "https://github.com/partrita/pubmed-miner"
