[book]
authors = ["Taeyoon Kim"]
language = "ko"
src = "book_src"
title = "Daily Papers Search"

[output.html]
additional-css = ["book_src/custom.css"]
git-repository-url = "https://github.com/partrita/pubmed-miner"
